
# asp_py_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'H<\t\xc8tV\xb4?\x0e/8*\xe5\xcc\x8a\x82'
    
_lr_action_items = {'IDENT':([0,5,6,7,15,17,],[3,3,9,9,9,9,]),'MIDENT':([0,5,],[4,4,]),'$end':([1,2,3,4,8,16,18,],[0,-2,-4,-6,-1,-3,-5,]),'SPACE':([2,3,4,16,18,],[5,-4,-6,-3,-5,]),'LP':([3,4,9,],[6,7,15,]),'STRING':([6,7,15,17,],[12,12,12,12,]),'NUM':([6,7,15,17,],[13,13,13,13,]),'COMMA':([9,11,12,13,21,],[-11,17,-10,-12,-9,]),'RP':([9,10,11,12,13,14,19,20,21,],[-11,16,-8,-10,-12,18,21,-7,-9,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'answerset':([0,5,],[1,8,]),'atom':([0,5,],[2,2,]),'terms':([6,7,15,17,],[10,14,19,20,]),'term':([6,7,15,17,],[11,11,11,11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> answerset","S'",1,None,None,None),
  ('answerset -> atom SPACE answerset','answerset',3,'p_answerset','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',76),
  ('answerset -> atom','answerset',1,'p_answerset','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',77),
  ('atom -> IDENT LP terms RP','atom',4,'p_atom','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',82),
  ('atom -> IDENT','atom',1,'p_atom','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',83),
  ('atom -> MIDENT LP terms RP','atom',4,'p_atom','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',84),
  ('atom -> MIDENT','atom',1,'p_atom','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',85),
  ('terms -> term COMMA terms','terms',3,'p_terms','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',99),
  ('terms -> term','terms',1,'p_terms','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',100),
  ('term -> IDENT LP terms RP','term',4,'p_term','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',108),
  ('term -> STRING','term',1,'p_term','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',109),
  ('term -> IDENT','term',1,'p_term','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',110),
  ('term -> NUM','term',1,'p_term','C:\\Anaconda\\lib\\site-packages\\pyasp\\parsing.py',111),
]
